# Generated by Django 4.1.7 on 2023-02-24 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_remove_category_image_category_image_file_namne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_file_namne',
        ),
        migrations.AddField(
            model_name='category',
            name='image_file_name',
            field=models.FileField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
