# Generated by Django 4.1.7 on 2023-02-25 12:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_category_image_file_namne_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image_file_name',
            field=models.FileField(blank=True, upload_to='catalog/images/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_on_drawing', models.CharField(max_length=3)),
                ('references', models.CharField(default='', max_length=1024)),
                ('part_number', models.CharField(max_length=7, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('part_replacement_number', models.CharField(max_length=7)),
                ('designation', models.CharField(max_length=128)),
                ('info', models.CharField(default='', max_length=64)),
                ('note', models.CharField(default='', max_length=64)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=12)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.category')),
            ],
        ),
    ]
