# Generated by Django 4.1.7 on 2023-02-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['category', 'position_on_drawing']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='keywords',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='part',
            name='info',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='part',
            name='note',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_replacement_number',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='part',
            name='position_on_drawing',
            field=models.CharField(blank=True, max_length=3, verbose_name='pos'),
        ),
        migrations.AlterField(
            model_name='part',
            name='references',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
