# Generated by Django 4.1.7 on 2023-02-25 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0006_alter_category_options_remove_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True)),
                ('specification', models.TextField(blank=True)),
                ('function_description', models.TextField(blank=True)),
                ('work_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=12)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.category')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
